### ISSUE TITLE
Project Dependencies Not Installing

### ISSUE THREAD

**Issue by 24anisha** [XeroAPI/xero-python-oauth2-starter#11]
I'm trying to follow the tutorial in order to build the starter app, but when i reach the step `pip install -r requirements.txt`, my terminal outputs a lot of error messages:

Collecting flask (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/f2/28/2a03252dfb9ebf377f40fba6a7841b47083260bf8bd8e737b0c6952df83f/Flask-1.1.2-py2.py3-none-any.whl
Collecting Flask-Session from git+https://github.com/SqrtMinusOne/flask-session.git@560d00f1a84a9924d788a4f4e1ef35c5cf94c76d#egg=Flask-Session (from -r requirements.txt (line 5))
  Cloning https://github.com/SqrtMinusOne/flask-session.git (to revision 560d00f1a84a9924d788a4f4e1ef35c5cf94c76d) to /private/var/folders/bg/y3y5xyh53w5f0b_4y9mrjyd40000gn/T/pip-install-8_kw6l5_/Flask-Session
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mitsuhiko/flask-sphinx-themes.git' into submodule path '/private/var/folders/bg/y3y5xyh53w5f0b_4y9mrjyd40000gn/T/pip-install-8_kw6l5_/Flask-Session/docs/_themes' failed
Failed to clone 'docs/_themes'. Retry scheduled
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mitsuhiko/flask-sphinx-themes.git' into submodule path '/private/var/folders/bg/y3y5xyh53w5f0b_4y9mrjyd40000gn/T/pip-install-8_kw6l5_/Flask-Session/docs/_themes' failed
Failed to clone 'docs/_themes' a second time, aborting
Command "git submodule update --init --recursive -q" failed with error code 1 in /private/var/folders/bg/y3y5xyh53w5f0b_4y9mrjyd40000gn/T/pip-install-8_kw6l5_/Flask-Session

However, according to my IDE (vs code, running inside the venv), none of the dependencies have been installed. What could be the issue?

I'm running macOS Catalina v 10.15.5

**Comment by SidneyAllen** [comment]
@24anisha - Are you still having issues?

I'm not 100% sure why you're getting this error.  Have you check that you SSH keys are setup for your github profile?
https://github.com/settings/keys

We ran into some issues with the current version of Flask-Session and had to point to a specific commit and download that code into our project.  But in order to do that your SSH keys need to be config.
https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

Let me know if this helps.

**Comment by mattarderne** [comment]
Above worked for me

**Comment by SidneyAllen** [comment]
closing this one off as resolved.
