### ISSUE TITLE
Redirect URI

### ISSUE THREAD

**Issue by mattarderne** [XeroAPI/xero-python-oauth2-starter#13]
I've tried a few, but in each case get 500 error when logging in. 
```
Error code: 500

Error: unauthorized_client : Invalid redirect_uri 
```
I've tried the following under `OAuth 2.0 redirect URIs` 
* `http://localhost:5000/`
* `https://xero.com/`
* `http://localhost:5000/callback`

**Comment by itsolver** [comment]
@mattarderne, I had this issue too. I recreated my app secret, clicked Save, updated in config.py, waited a few minutes, and now I've got an oauth token. redirect_uri working for me: http://localhost:5000/callback

**Comment by SidneyAllen** [comment]
@mattarderne - my advice was going to be check your "redirectURI" in developer.xero.com/mayapps

If you can share how you solved this, that would be cool.

**Comment by SidneyAllen** [comment]
@mattarderne  

Not sure what to say.  I'm setting the redirectUri in my Xero app (like you've done in the screenshot above)

And I'm running the python app.py on localhost:5000.

The code that sets the redirectURI on login is ...

`@app.route("/login")
def login():
    redirect_url = url_for("oauth_callback", _external=True)
    response = xero.authorize(callback_uri=redirect_url)
    return response

@app.route("/callback")
def oauth_callback():`

Which sets the redirectUri to "http://localhost:5000'

Unless you are running it locally with https or on a different port or changed the code, I'm not sure why you are getting the 500 error.

Have you watched this video on using the starter project?
https://www.youtube.com/watch?v=i8JWtbMo90M

**Comment by mattarderne** [comment]
@SidneyAllen still no luck, I made a fresh install, even tried running it on an ec2 instance but got stuck with the ssh issue on installing flask. Will let you know if I figure it out

**Comment by mattarderne** [comment]
Update on this:

Following `http://127.0.0.1:5000/` from the CLI causes the issue (maybe.. obviously! )
Following `http://localhost:5000/` allowed me to get the to the Oauth page

Proposed a fix
https://github.com/XeroAPI/xero-python-oauth2-starter/pull/15
