### ISSUE TITLE
installation script

### ISSUE THREAD

**Issue by pguerin3** [XeroAPI/xero-python-oauth2-starter#24]
Firstly - I have a valid SSH setup with Github as proven when I clone the xero-python-oauth2-starter repository:

"
[test@localhost ~]$ git clone git@github.com:XeroAPI/xero-python-oauth2-starter.git
Cloning into 'xero-python-oauth2-starter'...
Enter passphrase for key '/home/test/.ssh/id_rsa': 
remote: Enumerating objects: 177, done.
remote: Counting objects: 100% (177/177), done.
remote: Compressing objects: 100% (111/111), done.
remote: Total 177 (delta 89), reused 127 (delta 58), pack-reused 0
Receiving objects: 100% (177/177), 52.51 KiB | 193.00 KiB/s, done.
Resolving deltas: 100% (89/89), done.
[test@localhost ~]$
"

However I still get the connection error when I run 'pip install -r requirements.txt':

"
Collecting Flask-OAuthlib from git+https://github.com/ageis/flask-oauthlib.git@c5ea3ace957ceeeeab3cfb6556f32685ff292eab#egg=Flask-OAuthlib (from -r requirements.txt (line 8))
  Cloning https://github.com/ageis/flask-oauthlib.git (to c5ea3ace957ceeeeab3cfb6556f32685ff292eab) to /tmp/pip-build-s7ku_a84/Flask-OAuthlib
  Could not find a tag or branch 'c5ea3ace957ceeeeab3cfb6556f32685ff292eab', assuming commit.
fatal: unable to connect to github.com:
github.com[0: 140.82.114.3]: errno=Connection timed out

fatal: clone of 'git://github.com/lepture/flask-sphinx-themes.git' into submodule path '/tmp/pip-build-s7ku_a84/Flask-OAuthlib/docs/_themes' failed
Failed to clone 'docs/_themes'. Retry scheduled
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=Connection timed out
"

Also note that I am using the correct version of pip as I get the following warning at the end of the log:

"
You are using pip version 9.0.3, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
"

Any clues to what to troubleshoot next???

Note - I'm using Oracle Enterprise Linux 8.1.

**Comment by pguerin3** [comment]
I attempted to clone just the problem repo on it's own but I get the same error as for requirements.txt:

$ git clone git://github.com/lepture/flask-sphinx-themes.git
Cloning into 'flask-sphinx-themes'...
fatal: unable to connect to github.com:
github.com[0: 140.82.113.3]: errno=Connection timed out

**Comment by pguerin3** [comment]
If I do this, then it works:

$ git clone git@github.com:SqrtMinusOne/flask-session.git
Cloning into 'flask-session'...
remote: Enumerating objects: 288, done.
remote: Total 288 (delta 0), reused 0 (delta 0), pack-reused 288
Receiving objects: 100% (288/288), 73.79 KiB | 270.00 KiB/s, done.
Resolving deltas: 100% (157/157), done.
$ 

If I try to go to the URL in installation.txt:
https://github.com/SqrtMinusOne/flask-session.git@560d00f1a84a9924d788a4f4e1ef35c5cf94c76d#egg=Flask-Session
Then I get a 'does not exist error'.

**Comment by SidneyAllen** [comment]
@pguerin3 - I'm not sure what is different in your environment.  But I wanted to confirm that something hasn't changed in the code repos we are pulling into this example project.

So, I did the following.
1. Downloaded the xero-python-oauth2-starter project (not clone, but download) so I had a clean project.
2. Then I followed the steps in the README

- CD into unzipped download "xero-python-oauth2-starter-master"
- Created new python virtual environment by running _python3 -m venv venv_
- Activate new virtual environment by running _source venv/bin/activate_
- Install project dependencies by running _pip install -r requirements.txt_

All the dependencies installed without error.

I created my config.py file and set my client id and secret and successfully authenticated and made an API call.

**Comment by pguerin3** [comment]
ok - I've deleted all the Xero related directories, so I can start from scratch.
This is the log - note that I'm not cloning nor using wget.

[test@localhost ~]$ cd xero-python-oauth2-starter-master
[test@localhost xero-python-oauth2-starter-master]$ python3 -m venv venv
[test@localhost xero-python-oauth2-starter-master]$ source venv/bin/activate
(venv) [test@localhost xero-python-oauth2-starter-master]$ pip install -r requirements.txt
Collecting flask (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/f2/28/2a03252dfb9ebf377f40fba6a7841b47083260bf8bd8e737b0c6952df83f/Flask-1.1.2-py2.py3-none-any.whl
Collecting Flask-Session from git+https://github.com/SqrtMinusOne/flask-session.git@560d00f1a84a9924d788a4f4e1ef35c5cf94c76d#egg=Flask-Session (from -r requirements.txt (line 5))
  Cloning https://github.com/SqrtMinusOne/flask-session.git (to 560d00f1a84a9924d788a4f4e1ef35c5cf94c76d) to /tmp/pip-build-99ifet7f/Flask-Session
  Could not find a tag or branch '560d00f1a84a9924d788a4f4e1ef35c5cf94c76d', assuming commit.
Collecting Flask-OAuthlib from git+https://github.com/ageis/flask-oauthlib.git@c5ea3ace957ceeeeab3cfb6556f32685ff292eab#egg=Flask-OAuthlib (from -r requirements.txt (line 8))
  Cloning https://github.com/ageis/flask-oauthlib.git (to c5ea3ace957ceeeeab3cfb6556f32685ff292eab) to /tmp/pip-build-99ifet7f/Flask-OAuthlib
  Could not find a tag or branch 'c5ea3ace957ceeeeab3cfb6556f32685ff292eab', assuming commit.
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=Connection timed out

fatal: clone of 'git://github.com/lepture/flask-sphinx-themes.git' into submodule path '/tmp/pip-build-99ifet7f/Flask-OAuthlib/docs/_themes' failed
Failed to clone 'docs/_themes'. Retry scheduled
fatal: unable to connect to github.com:
github.com[0: 140.82.112.3]: errno=Connection timed out

fatal: clone of 'git://github.com/lepture/flask-sphinx-themes.git' into submodule path '/tmp/pip-build-99ifet7f/Flask-OAuthlib/docs/_themes' failed
Failed to clone 'docs/_themes' a second time, aborting
Command "git submodule update --init --recursive -q" failed with error code 1 in /tmp/pip-build-99ifet7f/Flask-OAuthlib
You are using pip version 9.0.3, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(venv) [test@localhost xero-python-oauth2-starter-master]$ 

**** I'm getting the same errors as before, and also note that I'm using pip 9.0.3. ****

**Comment by pguerin3** [comment]
@SidneyAllen
Looks like you have a privilege in github that I don't have.

**Comment by pguerin3** [comment]
I have identified the problem.
The Github instructions say this:
```
Paste the text below, substituting in your GitHub email address.
$ ssh-keygen -t ed25519 -C "your_email@example.com"

Note: If you are using a legacy system that doesn't support the Ed25519 algorithm, use:
$ ssh-keygen -t rsa -b 4096 -C "your_email@example.com"
```
So I had created SSH keys using the Ed25519 algorithm, and I got the issues above.
I now recreated the SSH keys using RSA, and the requirements.txt script executes without error.
