### ISSUE TITLE
When I try to install the dependencies I get this message.Pls Help

### ISSUE THREAD

**Issue by muthu-1812** [XeroAPI/xero-python-oauth2-starter#27]
pip install -r requirements.txt
Collecting Flask-Session
  Cloning https://github.com/SqrtMinusOne/flask-session.git (to revision 560d00f1a84a9924d788a4f4e1ef35c5cf94c76d) to c:\users\muthu\appdata\local\temp\pip-install-1iqp6jj_\flask-session_84fa9f68905241c99b8316874389d236
  Running command git clone -q https://github.com/SqrtMinusOne/flask-session.git 'C:\Users\muthu\AppData\Local\Temp\pip-install-1iqp6jj_\flask-session_84fa9f68905241c99b8316874389d236'
  Running command git rev-parse -q --verify 'sha^560d00f1a84a9924d788a4f4e1ef35c5cf94c76d'
  Running command git fetch -q https://github.com/SqrtMinusOne/flask-session.git 560d00f1a84a9924d788a4f4e1ef35c5cf94c76d
  Running command git checkout -q 560d00f1a84a9924d788a4f4e1ef35c5cf94c76d
  Running command git submodule update --init --recursive -q
  Host key verification failed.
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
  fatal: clone of 'git@github.com:mitsuhiko/flask-sphinx-themes.git' into submodule path 'C:/Users/muthu/AppData/Local/Temp/pip-install-1iqp6jj_/flask-session_84fa9f68905241c99b8316874389d236/docs/_themes' failed
  Failed to clone 'docs/_themes'. Retry scheduled
  Host key verification failed.
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
  fatal: clone of 'git@github.com:mitsuhiko/flask-sphinx-themes.git' into submodule path 'C:/Users/muthu/AppData/Local/Temp/pip-install-1iqp6jj_/flask-session_84fa9f68905241c99b8316874389d236/docs/_themes' failed
  Failed to clone 'docs/_themes' a second time, aborting
WARNING: Discarding git+https://github.com/SqrtMinusOne/flask-session.git@560d00f1a84a9924d788a4f4e1ef35c5cf94c76d#egg=Flask-Session. Command errored 
out with exit status 1: git submodule update --init --recursive -q Check the logs for full command output.
Collecting Flask-OAuthlib
  Cloning https://github.com/ageis/flask-oauthlib.git (to revision c5ea3ace957ceeeeab3cfb6556f32685ff292eab) to c:\users\muthu\appdata\local\temp\pip-install-1iqp6jj_\flask-oauthlib_a37eef437575472a8a94e10c96a214a0
  Running command git clone -q https://github.com/ageis/flask-oauthlib.git 'C:\Users\muthu\AppData\Local\Temp\pip-install-1iqp6jj_\flask-oauthlib_a37eef437575472a8a94e10c96a214a0'
  Running command git rev-parse -q --verify 'sha^c5ea3ace957ceeeeab3cfb6556f32685ff292eab'
  Running command git fetch -q https://github.com/ageis/flask-oauthlib.git c5ea3ace957ceeeeab3cfb6556f32685ff292eab
  Running command git checkout -q c5ea3ace957ceeeeab3cfb6556f32685ff292eab
  Running command git submodule update --init --recursive -q
Requirement already satisfied: flask in c:\users\muthu\desktop\recko\xero_demo\env2\lib\site-packages (from -r requirements.txt (line 1)) (1.1.2)     
ERROR: Could not find a version that satisfies the requirement flask-session (unavailable)
ERROR: No matching distribution found for flask-session (unavailable)

**Comment by Umlatt** [comment]
Good day.

I have hit the same issue. What was the resolution?

**Comment by SidneyAllen** [comment]
Hi @Umlatt - glad you figured this out.

I'm not sure how you arrived on "need to be tracked".  The starter app was built using Flask but we found some bugs and to work around them we are pulling a patched version of the libraries.

There are comments in the requirements.txt file if you're interested in the details.

**Comment by SidneyAllen** [comment]
@Umlatt - Looking at these dependencies again, it looks like they've been patched and we can point to the main repositories on pypi to avoid others from hitting this issue.

Thanks again for your feedback.

**Comment by Umlatt** [comment]
> @Umlatt - Looking at these dependencies again, it looks like they've been patched and we can point to the main repositories on pypi to avoid others from hitting this issue.
> 
> Thanks again for your feedback.

Apologies for the delay. Thanks for the update. Have a great one.

**Comment by Umlatt** [comment]
> Hi @Umlatt - glad you figured this out.
> 
> I'm not sure how you arrived on "need to be tracked". The starter app was built using Flask but we found some bugs and to work around them we are pulling a patched version of the libraries.
> 
> There are comments in the requirements.txt file if you're interested in the details.

I was just being unnecessarily facetious (aimed at Microsoft). But all is well. Thanks again for the support.
