### ISSUE TITLE
Using python for integration without UI

### ISSUE THREAD

**Issue by nikhilfsoft** [XeroAPI/xero-python-oauth2-starter#28]
I am working on business use case where I have to integrate with Xero for BI reporting purposes. I was able to follow the instructions on the github page to set it up for myself but the integration is UI based.
I could use the instructions given on following page to generate all necessary tokens for with non-UI integrations:
https://developer.xero.com/documentation/api-guides/machine-2-machine

But now I am struggling with tweaking the python SDK to use as a back-end integration where I could just consume the data from Xero without any UI.
It would be great help if there are any suggestions regarding using python SDK for without UI integration.
Pardon my lack of expertise in python to achieve the same if it was very straight forward. Being a BI profession this is only SDK I could understand and make it work for Xero integration.

**Comment by RettBehrens** [comment]
Hey @nikhilfsoft could add a bit more info on where/how you're stuck so that I can better assist you with your use case?

**Comment by nikhilfsoft** [comment]
Hi @RettBehrens 
So basically my aim is to have a python script which runs everyday through scheduler to fire a set of API to get responses for some KPIs. So the python SDK in its current form does not help much as it requires an active http session.
Here are the things I have done so far:
1. Configure **xero-python-oauth2-starter** SDK to work with my Xero account.
2. I was able add additional menu options to call APIs for accounts and journals. (Basically I need accounts and journals for my KPIs). But so far all works out only through a http page. What I understand from code that there is active session object which holds all necessary tokens for APIs to work.
3. Next I followed instructions on link : https://developer.xero.com/documentation/api-guides/machine-2-machine
I have now successfully generated access token, refresh token and identity token for offline and back-end API calls.

Now I was trying to figure out how to use these tokens to tweak the python SDK so that I can have a stand-alone script to call APIs.
To achieve that I started to reverse engineer to API calls. For example:
Here is call to get invoices in SDK:
`    invoices = accounting_api.get_invoices(
        xero_tenant_id, statuses=["DRAFT", "SUBMITTED"]
    )`
The call requires xero_tenant_id which is returned by function get_xero_tenant_id(). If I get into function get_xero_tenant_id() the very step is
`token = obtain_xero_oauth2_token()`
Now this is where I am stuck. Now I am not sure how can I use the tokens I generated in step 3 above and when let run the function as is without http page I get following error:

**Message=Working outside of request context.
This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.**

As mentioned I have very limited expertise in python so not sure if my approach is right here or if I can use the SDK for stand-alone API calls. Happy to share more details if needed.

**Comment by RettBehrens** [comment]
Ah, ok. So we use the session in lieu of a database in our sample apps. To clarify, the SDK itself does not require session to my knowledge, but the sample apps do. `obtain_xero_oauth2_token()` could just as easily be rewritten to get the tokens from a db in your use case. Hope this helps to get you unstuck!

**Comment by nikhilfsoft** [comment]
Thanks for that. I got some success but I believe my code still not that refined and optimized. I will put up my code here for a quick review once it is in some decent shape.
